//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PostMost.rc
//
#define VS_VERSION_INFO                 1
#define IDOK                            1
#define IDS_FILENAME                    1
#define IDCANCEL                        2
#define IDS_DIRECTORY                   2
#define IDSKIP                          3
#define IDS_NEWSGROUPS_TOO_MANY_NEWSGROUPS_SELECTED 3
#define IDS_NEWSGROUPS_NO_NEWSGROUPS_SELECTED 4
#define IDS_NEWSGROUP                   5
#define IDS_NO_GROUPS_SELECTED          6
#define IDS_SUBJECT_LINE_UNCHANGED      7
#define IDS_SUBJECT_LINE_MISSING_DOLLARF 8
#define IDS_APP_ERROR_NO_OBJECT_TO_APPLY_SETTINGS 9
#define IDS_NO_NEWSGROUP_SELECTED       10
#define IDS_HEADERS_FROM_REQUIRED       11
#define IDS_PROGRAM_INVALID_MAX_LINES   12
#define IDS_DEV_ERROR_NO_OBJECT_TO_APPLY_SETTINGS 13
#define IDS_NEWSSERVER_NAME_TOO_LONG    14
#define IDS_NEWSSERVER_INVALID_PORT     15
#define IDS_IDS_NEWSSERVER_USERNAME_TOO_LONG 16
#define IDS_NEWSSERVER_PASSWORD_TOO_LONG 17
#define IDS_IDS_NEWSSERVER_CONFIRM_PASSWORD_TOO_LONG 18
#define IDS_NEWSSERVER_PASSWORD_MISMATCH 19
#define IDS_ENTER_NUMBER_RANGE_1_TO_10000 20
#define IDS_NUMBER_OUT_OF_RANGE_1000_TO_32000 21
#define IDS_SELECT_PARTS_TO_POST        22
#define IDS_TOO_MANY_GROUPS_SELECTED    23
#define IDS_TARGET_NEWSGROUPS           24
#define IDS_LOG_ITEM_TEXT               25
#define IDS_DELETE_TASK_LOG_HISTORY     26
#define IDS_ARTICLE_SUBJECT_LINE        27
#define IDS_PARTS_TO_POST               28
#define IDS_POSTING_RESULT              29
#define IDS_NEWSGROUPS                  30
#define IDS_DISCLAIMER                  31
#define IDS_ERROR_WINDOW_DND_TARGET     32
#define IDS_INVALID_DND_FORMAT          33
#define IDS_NO_FILES_TO_ADD             34
#define IDS_NO_GROUP_NAME_ENTERED       35
#define IDS_GROUP_NAME_LENGTH_EXCEEDED  36
#define IDS_CHECKSUMS_PART_SIZE_MULTIPLE_64 37
#define IDS_NO_GROUPS_SELECTED_STERN    38
#define IDS_HISTORY_ARTICLE_SUBJECT     39
#define IDS_HISTORY_POSTED              40
#define IDS_HISTORY_DATE_SAVED          41
#define IDS_HISTORY_ERROR_OPENING_FILE  42
#define IDS_STRING43                    43
#define IDS_HISTORY_INFO_LABEL          43
#define IDS_NEWSGROUP_ADD_EXISTING_GROUP 44
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDD_PROPPAGE_SERVER             106
#define IDD_PROPPAGE_HEADERS            107
#define IDD_PROPPAGE_GROUPS             108
#define IDR_MAINFRAME                   128
#define IDR_POSTMOTYPE                  129
#define IDD_DIALOG_ADDGROUP             130
#define IDD_INSERT_DROPPED_FILES_DLG    133
#define IDD_DIALOG_PROGRESS             134
#define IDD_PROPPAGE_PROGRAM_SETTINGS   135
#define ID_BITMAP_IMAGELIST             135
#define IDD_PROPPAGE_TASK_ITEM_MAIN     136
#define IDD_PROPPAGE_TASK_ITEM_GROUPS   137
#define IDD_PROPPAGE_TASK_ITEM_PREFIX_TEXT 138
#define IDD_PROPPAGE_TASK_ITEM_LOG      139
#define IDB_BITMAP_SPLASH               160
#define IDB_STATEICONS                  161
#define IDD_DIALOG_MAX_LINES            164
#define IDD_DIALOG_POSTMOST_HISTORY     165
#define IDB_BITMAP_ABOUT                168
#define IDR_WAVE_HISTORY_ERASER         169
#define IDD_DIALOG_DEL_HIST             170
#define IDI_ICON_QUESTION               171
#define IDD_DIALOG_AUTO_RETRY           172
#define IDI_ICON_ERROR                  173
#define IDD_DIALOG_DEL_TASK             174
#define IDD_PROPPAGE_ADD_SUBJECT        175
#define IDD_PROPPAGE_ADD_TEXT_PREFIX    176
#define IDR_MENU_CONTEXT                177
#define IDD_PROPPAGE_ADD_GROUPS         177
#define IDR_WAVE_GROOVY                 178
#define IDD_DIALOG_POST_AT              179
#define IDI_ICON_STOP_WATCH             180
#define IDD_PROPPAGE_ADD_ORDER          180
#define IDI_ICON_TRAY_READY             181
#define IDI_ICON_TRAY_POSTING           182
#define IDI_ICON_TRAY_ERROR             183
#define IDI_ICON_TRAY_WAITING           184
#define IDD_PROPPAGE_ADD_CHECKSUMS      185
#define IDD_PROPPAGE_ADD_RECOVERY       186
#define IDD_DIALOG_ENCODING             187
#define IDB_SKIN2_TOOLBAR               188
#define IDC_EDIT_SERVER                 1000
#define IDC_CHECK_LOGIN                 1001
#define IDC_EDIT_USERNAME               1002
#define IDC_LIST_GROUPS                 1002
#define IDC_EDIT_PASSWORD               1003
#define IDC_BUTTON_ADD                  1003
#define IDC_EDIT_CONFIRM                1004
#define IDC_EDIT_REPLYTO                1004
#define IDC_BUTTON_REMOVE               1004
#define IDC_EDIT_ORG                    1005
#define IDC_EDIT_MAXLINES               1005
#define IDC_EDIT_SUBJECT                1006
#define IDC_EDIT_PORT                   1006
#define IDC_EDIT_ORGANIZATION           1006
#define IDC_EDIT_BWCAP                  1007
#define IDC_EDIT_FROM                   1007
#define IDC_EDIT_FROM_NICK              1008
#define IDC_EDIT_GROUP                  1008
#define IDC_CHECK_COUNTER               1009
#define IDC_EDIT_FOLLOWUPTO             1009
#define IDC_EDIT_DOMAINID               1010
#define IDC_CHECK_INSERT_HEAD           1010
#define IDC_EDIT_SUBJPREFIX             1011
#define IDC_EDIT_CUR_FILE               1012
#define IDC_EDIT_CUR_ARTICLE            1014
#define IDC_STATIC_TIME_ELAPSED         1015
#define IDC_STATIC_TIME_STARTED         1016
#define IDC_PROGRESS_BATCH              1017
#define IDC_PROGRESS_FILE               1018
#define IDC_CHECK_PROCESS_DIRECTORIES   1018
#define IDC_EDIT_CUR_ARTICLE2           1018
#define IDC_PROGRESS_BATCH2             1018
#define IDC_PROGRESS_ARTICLE            1019
#define IDC_CHECK_HL_LAST               1019
#define IDC_PROGRESS_ARTICLE1           1019
#define IDC_CHECK_SHOWPROGRESSONSTART   1020
#define IDC_STATIC_TIME_TOGO            1020
#define IDC_STATIC_VERSION              1020
#define IDC_CHECK_SOUND                 1021
#define IDC_CHECK_ENUMBYDIR             1021
#define IDC_PROGRESS_ARTICLE2           1021
#define IDC_CHECK_FILENOFN_DEFAULT      1022
#define IDC_CHECK_SYSTRAY               1022
#define IDC_CHECK_RECURSIVE             1022
#define IDC_EDIT_CUR_ARTICLE3           1022
#define IDC_BUTTON_GO                   1022
#define IDC_CHECK_SORTFILES             1023
#define IDC_CHECK_XNOARCHIVE            1023
#define IDC_PROGRESS_ARTICLE3           1023
#define IDC_BUTTON_GO_MAIL              1023
#define IDC_CHECK_SHOWDIALOG            1024
#define IDC_CHECK_AUTORETRY             1024
#define IDC_CHECK_XSERVERDATE           1024
#define IDC_EDIT_CUR_ARTICLE4           1024
#define IDC_CHECK_DETECTPAR2            1025
#define IDC_CHECK_FILETHREAD            1025
#define IDC_PROGRESS_ARTICLE4           1025
#define IDC_EDIT_TEXT_PREFIX            1026
#define IDC_CHECK_HEADERPARTIAL         1026
#define IDC_EDIT_CUR_ARTICLE5           1026
#define IDC_PROGRESS_FILE1              1027
#define IDC_PROGRESS_FILE2              1028
#define IDC_PROGRESS_FILE3              1029
#define IDC_PROGRESS_FILE4              1030
#define IDC_PROGRESS_ARTICLE5           1031
#define IDC_PROGRESS_FILE5              1032
#define IDC_EDIT_CUR_ARTICLE6           1033
#define IDC_PROGRESS_ARTICLE6           1034
#define IDC_PROGRESS_FILE6              1035
#define IDC_EDIT_CUR_ARTICLE7           1036
#define IDC_PROGRESS_ARTICLE7           1037
#define IDC_EDIT_TASK_SUBJECT           1038
#define IDC_PROGRESS_FILE7              1038
#define IDC_EDIT_TASK_FILENAME          1039
#define IDC_EDIT_CUR_ARTICLE8           1039
#define IDC_LABEL_FILE_INFO             1040
#define IDC_PROGRESS_ARTICLE8           1040
#define IDC_EDIT_TASK_MAX_LINES         1041
#define IDC_PROGRESS_FILE8              1041
#define IDC_LIST_TASK_PARTS             1042
#define IDC_EDIT_CUR_ARTICLE9           1042
#define IDC_LIST_TARGET_GROUPS          1043
#define IDC_PROGRESS_ARTICLE9           1043
#define IDC_BUTTON_TASK_ADD_GROUP       1044
#define IDC_PROGRESS_FILE9              1044
#define IDC_EDIT_TASK_ITEM_PREFIX_TEXT  1045
#define IDC_EDIT_CUR_ARTICLE10          1045
#define IDC_PROGRESS_ARTICLE10          1046
#define IDC_BUTTON_TASK_ITEM_CLEAR_LOG  1047
#define IDC_PROGRESS_FILE10             1047
#define IDC_BUTTON_PARTS_MODIFY         1048
#define IDC_EDIT_CUR_ARTICLE11          1048
#define IDC_BUTTON_TASK_PARTS_CHECK_ALL 1049
#define IDC_PROGRESS_ARTICLE11          1049
#define IDC_BUTTON_TASK_PARTS_UNCHECK_ALL 1050
#define IDC_PROGRESS_FILE11             1050
#define IDC_CHECK_TASK_POST_PREFIX_TEXT 1051
#define IDC_EDIT_CUR_ARTICLE12          1051
#define IDC_EDIT_NEW_MAX_LINES          1052
#define IDC_PROGRESS_ARTICLE12          1052
#define IDC_LIST_TASK_LOG               1053
#define IDC_PROGRESS_FILE12             1053
#define IDC_LIST_HISTORY                1054
#define IDC_BUTTON_HIST_COMPACT         1058
#define IDC_BUTTON_HIST_DEL_SEL         1059
#define IDC_BUTTON_HIST_QUEUE_SEL       1060
#define IDC_LABEL_HISTORY_INFO          1061
#define IDC_STATIC_IMAGE                1062
#define IDC_HIST_DEL_LABEL              1064
#define IDC_STATIC_INFO                 1065
#define IDC_STATIC_RETRY_INFO           1066
#define IDC_STATIC_LABEL                1068
#define IDC_CHECK_SAVE_TO_HISTORY       1069
#define IDC_STATIC_PART_INFO            1070
#define IDC_STATIC_FILE_INFO            1071
#define IDC_STATIC_N_CHECKED            1071
#define IDC_EDIT_GROUPS                 1073
#define IDC_EDIT_GROUPS2                1074
#define IDC_STATIC_EX_OUTPUT            1075
#define IDC_EDIT_GROUPS3                1075
#define IDC_RADIO_PREFIX_ALL            1076
#define IDC_EDIT_GROUPS4                1076
#define IDC_RADIO_PREFIX_FIRST_ONLY     1077
#define IDC_EDIT_GROUPS5                1077
#define IDC_EDIT_PREFIX_TEXT            1078
#define IDC_EDIT_GROUPS6                1078
#define IDC_EDIT_GROUPS7                1079
#define IDC_BUTTON_ADD_GROUP            1080
#define IDC_EDIT_GROUPS8                1080
#define IDC_EDIT_SUBJECT_TEMPLATE       1081
#define IDC_EDIT_GROUPS9                1081
#define IDC_CHECK_SEND_TEXT_PREFIX      1082
#define IDC_EDIT_GROUPS10               1082
#define IDC_STATIC_EXAMPLE_INFO         1083
#define IDC_EDIT_GROUPS11               1083
#define IDC_STATIC_TIME                 1084
#define IDC_EDIT_GROUPS12               1084
#define IDC_COMBO_HOUR                  1085
#define IDC_COMBO_MIN                   1086
#define IDC_STATIC_GRAPH                1087
#define IDC_COMBO_AM_PM                 1087
#define IDC_LIST_FILE_ORDER             1088
#define IDC_BUTTON_AFO_UP               1089
#define IDC_BUTTON_AFO_DOWN             1090
#define IDC_BUTTON_AFO_SORTPAR          1091
#define IDC_COMBO_SERVER                1092
#define IDC_BUTTON1                     1093
#define IDC_BUTTON_AFO_DELFILE          1093
#define IDC_COMBO_HOUR_END              1094
#define IDC_COMBO_MIN_END               1095
#define IDC_COMBO_AM_PM_END             1096
#define IDC_STATIC_TIME_END             1097
#define IDC_CHECK_STOP                  1098
#define IDC_CHECK_REPEAT                1099
#define IDC_LIST_FILE_ORDER2            1101
#define IDC_CONNECTIONS                 1103
#define IDC_CHECK_SFV                   1104
#define IDC_EDIT_SFV                    1105
#define IDC_CHECK_GROUPTHREAD           1106
#define IDC_CHECK_SAMESIZE              1107
#define IDC_BUTTON_SFV                  1107
#define IDC_TEXT_PAR2_INFO              1108
#define IDC_EDIT_PAR2                   1111
#define IDC_EDIT_FIRST                  1112
#define IDC_CHECK_PAR2                  1112
#define IDC_EDIT_BLOCKS                 1113
#define IDC_BUTTON_PAR2                 1113
#define IDC_EDIT_FILES                  1114
#define IDC_EDIT_PARTSIZE               1114
#define IDC_SPIN_FIRST                  1115
#define IDC_EDIT_NZB                    1115
#define IDC_SPIN_BLOCKS                 1116
#define IDC_CHECK_NZB                   1116
#define IDC_SPIN_FILES                  1117
#define IDC_BUTTON_NZB                  1117
#define IDC_TEXT_NBFILES                1118
#define IDC_TEXT_RECVSIZE               1119
#define IDC_LIST_ENCODING               1121
#define IDC_EDIT_CONNECTIONS            1122
#define IDC_SPIN_CONNECTIONS            1123
#define IDC_EDIT_STATUS                 1123
#define IDC_COMBO_PRIORITY              1124
#define IDC_TEXT_SPEED                  1125
#define IDC_COMBO_SKIN                  1126
#define ID_POST_START                   32771
#define ID_POST_STOP                    32772
#define ID_POST_SETTINGS                32773
#define ID_POST_THREADS                 32777
#define ID_FILE_REMOVEALL               32778
#define ID_FILE_CLEARLIST               32779
#define ID_FILE_CLEARDONE               32780
#define ID_FILE_CLEAR_ERRORS            32781
#define ID_FILE_QUEUE_ALL               32782
#define ID_FILE_ADDFILES                32783
#define ID_FILE_CLEARSELECTED           32784
#define ID_FILE_HISTORY                 32785
#define ID_FILE_TASK_PROPERTIES         32786
#define ID_BTN_HIST_CLEAR               32787
#define ID_BTN_HIST_CLEAR_SEL           32789
#define ID_BTN_HIST_QUEUE_SEL           32790
#define ID_FILE_QUEUE_SEL               32791
#define ID_FILE_REASSIGN_NEWSGROUPS     32795
#define ID_POST_START_AT                32796
#define ID_MOVE_TASK_UP                 32797
#define ID_MOVE_TASK_DOWN               32798
#define ID_MOVE_TASK_TOP                32799
#define ID_MOVE_TASK_BOTTOM             32800
#define ID_FILE_SET_HOLD                32801
#define ID_GENERATE_PAR2_VOL            32802
#define ID_POST_ENCODES                 32806
#define ID_ENCODE_START                 32807
#define ID_ENCODE_STOP                  32808
#define AFX_IDS_APP_TITLE               0xE000
#define AFX_IDS_IDLEMESSAGE             0xE001
#define ID_FILE_NEW                     0xE100
#define ID_FILE_OPEN                    0xE101
#define ID_FILE_CLOSE                   0xE102
#define ID_FILE_SAVE                    0xE103
#define ID_FILE_SAVE_AS                 0xE104
#define ID_FILE_MRU_FILE1               0xE110
#define ID_FILE_MRU_FILE2               0xE111
#define ID_FILE_MRU_FILE3               0xE112
#define ID_FILE_MRU_FILE4               0xE113
#define ID_FILE_MRU_FILE5               0xE114
#define ID_FILE_MRU_FILE6               0xE115
#define ID_FILE_MRU_FILE7               0xE116
#define ID_FILE_MRU_FILE8               0xE117
#define ID_FILE_MRU_FILE9               0xE118
#define ID_FILE_MRU_FILE10              0xE119
#define ID_FILE_MRU_FILE11              0xE11A
#define ID_FILE_MRU_FILE12              0xE11B
#define ID_FILE_MRU_FILE13              0xE11C
#define ID_FILE_MRU_FILE14              0xE11D
#define ID_FILE_MRU_FILE15              0xE11E
#define ID_FILE_MRU_FILE16              0xE11F
#define ID_EDIT_CLEAR                   0xE120
#define ID_EDIT_CLEAR_ALL               0xE121
#define ID_EDIT_COPY                    0xE122
#define ID_EDIT_CUT                     0xE123
#define ID_EDIT_FIND                    0xE124
#define ID_EDIT_PASTE                   0xE125
#define ID_EDIT_REPEAT                  0xE128
#define ID_EDIT_REPLACE                 0xE129
#define ID_EDIT_SELECT_ALL              0xE12A
#define ID_EDIT_UNDO                    0xE12B
#define ID_EDIT_REDO                    0xE12C
#define ID_WINDOW_SPLIT                 0xE135
#define IDS_STRING57654                 57654
#define ID_APP_ABOUT                    0xE140
#define ID_APP_EXIT                     0xE141
#define ID_NEXT_PANE                    0xE150
#define ID_PREV_PANE                    0xE151
#define ID_INDICATOR_EXT                0xE700
#define ID_INDICATOR_CAPS               0xE701
#define ID_INDICATOR_NUM                0xE702
#define ID_INDICATOR_SCRL               0xE703
#define ID_INDICATOR_OVR                0xE704
#define ID_INDICATOR_REC                0xE705
#define ID_VIEW_TOOLBAR                 0xE800
#define ID_VIEW_STATUS_BAR              0xE801
#define AFX_IDS_SCSIZE                  0xEF00
#define AFX_IDS_SCMOVE                  0xEF01
#define AFX_IDS_SCMINIMIZE              0xEF02
#define AFX_IDS_SCMAXIMIZE              0xEF03
#define AFX_IDS_SCNEXTWINDOW            0xEF04
#define AFX_IDS_SCPREVWINDOW            0xEF05
#define AFX_IDS_SCCLOSE                 0xEF06
#define IDS_STRING61191                 61191
#define IDS_STRING61192                 61192
#define AFX_IDS_SCRESTORE               0xEF12
#define AFX_IDS_SCTASKLIST              0xEF13
#define IDS_POSTMOST_VERSION_INFO       61204
#define IDS_POSTMOST_VERSION            61205
#define ID_INDICATOR_FILES              61206
#define ID_INDICATOR_TASK               61207

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        189
#define _APS_NEXT_COMMAND_VALUE         32809
#define _APS_NEXT_CONTROL_VALUE         1127
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
